#
#  ▄▀█ █░░ █▄▀ ▄▀█ █▀▀ █▀▄ ▄▀█ ▄▀█ █░█ █░█ █▀▀ █▀▀
#  █▀█ █▄▄ █░█ █▀█ ██▄ █▄▀ █▀█ █▀█ ▀▄▀ █▀█ █▄▄ █▀░
#
#               Plugin by nmoralesFZ
#             Discord: nmoralesFZ#2607            
#  Descárgalo desde: https://www.nmoralesfz.tk/s/av

server_name: "&l&bTu&fServer" # Soporte para coloreado con & (no uses § o no funcionará).
map_number: "1" # Sólo números, sin letras.
URL: "https://discord.com/api/webhooks/" # Ingresa tu webhook para anunciar KOTH's y otras cosas.

# --------------------------------------------------------
# 🢃 Menú de kits inicia aquí 🢃
kits:
  menu.name: '&l&bKits'
  item.slot.empty: '0:0'
  item.kit.lore:
    - ''
    - '&bTiempo de espera: &7{kit_cooldown}'
    - '&bTu tiempo de espera: &7{player_cooldown}'
    - '&bCompra este kit y mucho más en &l&o&ftienda.tuip.com&r'
# 🢁 Menú de kits termina aquí 🢁 
# --------------------------------------------------------
# 🢃 Configuración de cooldowns (tiempos de espera) inicia aquí 🢃
Global:
Cooldowns:
  EnderPearl: 15
  CombatTag: 30
  ArcherTag: 10
  LoggerBait: 30
  Apple: 15
  EggPort: 15
  SpecialItem: 15
  StormBreaker: 120
  Bard: 120
  RogueItem: 15
  Berserk: 120
  NinjaShear: 120
  PotionCounter: 90
  AntiTrapper: 120
  AntiTrapperTarget: 20
  Home: 10
  Stuck: 35
  Logout: 16
# 🢁 Configuración de cooldowns (tiempos de espera) termina aquí 🢁 
# --------------------------------------------------------
# 🢃 Configuración de factions inicia aquí 🢃
FactionsConfig:
  maxPlayers: 12
  SpreadWater: true
  BorderLimit: 2000
  Warzone: 300
# 🢁 Configuración de factions termina aquí 🢁 
# --------------------------------------------------------
# 🢃 Configuración de dimensiones inicia aquí 🢃
LevelManager:
  EntitySpawnDelay: 400
  levelEndName: "endav"
  levelNetherName: "netherav"
block_ids: ["119:0", "120:0"]
items_id: ["46:0", "259:0, 2257:0"]
# 🢁 Configuración de dimensiones termina aquí 🢁 
