#         _ _                  _                   
#        | | |                | |                  
#    __ _| | | ____ _  ___  __| | __ _  __ ___   __
#   / _` | | |/ / _` |/ _ \/ _` |/ _` |/ _` \ \ / /
#  | (_| | |   < (_| |  __/ (_| | (_| | (_| |\ V / 
#  \__,_|_|_|\_\__,_|\___|\__,_|\__,_|\__,_| \_/  
#
#               Plugin by alkaedaav
#             Discord: alkaedaav#9877                   

server_name: "&l&5HCF" # Coloring support.
map_number: "1" # Only number, no letters.
URL: "https://discord.com/api/webhooks/"
kits:
  menu.name: '&l&5HCFKits'
  item.slot.empty: '0:0'
  item.kit.lore:
    - ''
    - '&bCooldown time: &7{kit_cooldown}'
    - '&bYour cooldown time: &7{player_cooldown}'
    - '&bBuy this awesome kit and more on &l&o&fstore.HCF.gq&r'
MySQL:
  hostname: "DATABASE HERE"
  username: "DATABASE HERE"
  password: "DATABASE HERE"
  database: "DATABASE HERE"
  port: 3306
Global:
Cooldowns:
  EnderPearl: 15
  CombatTag: 30
  ArcherTag: 10
  LoggerBait: 30
  Apple: 15
  EggPort: 15
  SpecialItem: 15
  StormBreaker: 120
  Bard: 120
  RogueItem: 15
  Berserk: 120
  NinjaShear: 120
  PotionCounter: 90
  AntiTrapper: 120
  AntiTrapperTarget: 20
  Home: 10
  Stuck: 35
  Logout: 16
FactionsConfig:
  maxPlayers: 12
  SpreadWater: true
  BorderLimit: 2000
  Warzone: 300
  
  # Coming soon
LevelManager:
  EntitySpawnDelay: 400
  levelEndName: "End"
  levelNetherName: "Nether"
block_ids: ["119:0", "120:0"]
items_id: ["46:0", "259:0, 2257:0"]
