---
#         _ _                  _                   
#        | | |                | |                  
#    __ _| | | ____ _  ___  __| | __ _  __ ___   __
#   / _` | | |/ / _` |/ _ \/ _` |/ _` |/ _` \ \ / /
#  | (_| | |   < (_| |  __/ (_| | (_| | (_| |\ V / 
#  \__,_|_|_|\_\__,_|\___|\__,_|\__,_|\__,_| \_/  
#
#               Plugin by alkaedaav
#             Discord: alkaedaav#9877                            



server_ip: "lunaria.gq:19012"
scoreb_lines: "" # 15 lines recommended
StormBreaker: "&5&lStormBreaker&8» &r&7{time} "
AntiTrapper: "&5&lAntiTrapper&8» &r&7{time} "
Bard: "&5&lZombieBard&8» &r&7{time} "
RogueItem: "&5&lRogue Sword&8» &r&7{time} "
Berserk: "&5&lBerserk&8» &r&7{time} "
EggPort: "&5&lEggPort&8» &r&7{time} "
SpecialItem: "&l&5Partner Item&8» &r&7{time} "
NinjaShear: "&l&5NinjaShear&8» &r&7{time} "
PotionCounter: "&l&5PotionCounter&8» &r&7{time} "
EnderPearl: "&5&lEnderPearl&8» &r&7{time} "
CombatTag: "&5&lCombatTag&8» &r&7{time} "
Apple: "&5&lApple&8» &r&7{time} "
Logout: "&5&lLogout&8» &r&7{time} "
Home: "&5&lHome&8» &r&7{time} "
Stuck: "&5&lStuck&8» &r&7{time} "
SOTW: "&5&lSOTW&8» &r&7{time} "
EOTW: "&5&lEOTW&8» &r&7{time} "
KOTH: "&l&5{kothName}&8» &r&7{time} "
SALE: "&5&lRestart&8» &r&7{time}"
PP: "&l&5PP All in&8» &r&7{time} "
Airdrop: "&l&5Airdrop all in&8» &r&7{time} "
Invincibility: "&5&lPvP Timer&8» &r&7{time} "
BardEnergy: "&5&lBardEnergy&8» &r&c{bardEnergy} "
ArcherEnergy: "&5&lArcherEnergy&8» &r&c{archerEnergy} "
MageEnergy: "&5&lMageEnergy&8» &r&c{mageEnergy} "
factionFocus: [ 
  "&l&5Faction&8» &r&7{factionName} ", 
  "&l&5Focus HQ&8» &r&7{factionHome} ", 
  "&l&5DTR&8» &r&7{factionDTR} ", 
  "&l&5Online&8» &r&7{factionOnlinePlayers} ", 
]