---
#
#  ▄▀█ █░░ █▄▀ ▄▀█ █▀▀ █▀▄ ▄▀█ ▄▀█ █░█ █░█ █▀▀ █▀▀
#  █▀█ █▄▄ █░█ █▀█ ██▄ █▄▀ █▀█ █▀█ ▀▄▀ █▀█ █▄▄ █▀░
#
#               Plugin by nmoralesFZ
#             Discord: nmoralesFZ#2607            
#  Descárgalo desde: https://www.nmoralesfz.tk/s/av    



server_ip: "jugar.tuip.com"
scoreb_lines: "" # Separador para la scoreboard (recomendado 15 líneas)
hq_service: "  §9HQ§8:"
StormBreaker: "  &eStormBreaker&8: &r&f{time} "
AntiTrapper: "  &eAntiTrapper&8: &r&f{time} "
Bard: "  &eZombieBard&8: &r&f{time} "
RogueItem: "  &eRogue Sword&8: &r&f{time} "
Berserk: "  &eBerserk&8: &r&f{time} "
EggPort: "  &eEggPort&8: &r&f{time} "
SpecialItem: "  &ePartner Item&8: &r&f{time} "
NinjaShear: "  &eNinjaShear&8: &r&f{time} "
PotionCounter: "  &ePotionCounter&8: &r&f{time} "
EnderPearl: "  &eEnderPearl&8: &r&f{time} "
CombatTag: "  &eCombatTag&8: &r&f{time} "
Apple: "  &6Apple&8: &r&f{time} "
Logout: "  &6Logout&8: &r&f{time} "
Home: "  &6Home&8: &r&f{time} "
Stuck: "  &6Stuck&8: &r&f{time} "
SOTW: "  &aSOTW&8: &r&f{time} "
EOTW: "  &cEOTW&8: &r&f{time} "
KOTH: "  &4{kothName}&8: &r&f{time} "
SALE: "  &dRestart&8: &r&f{time}"
PP: "  &dPP All in&8: &r&f{time} "
Airdrop: "  &dAirdrop all in&8: &r&f{time} "
Invincibility: "  &2PvP Timer&8: &r&f{time} "
BardEnergy: "  &5BardEnergy&8: &r&c{bardEnergy} "
ArcherEnergy: "  &5ArcherEnergy&8: &r&c{archerEnergy} "
MageEnergy: "  &5MageEnergy&8: &r&c{mageEnergy} "
factionFocus: [ 
  "  &bFaction&8: &r&f{factionName} ", 
  "  &bFocus HQ&8: &r&f{factionHome} ", 
  "  &bDTR&8: &r&f{factionDTR} ", 
  "  &bOnline&8: &r&f{factionOnlinePlayers} ", 
]