---
#
#  ▄▀█ █░░ █▄▀ ▄▀█ █▀▀ █▀▄ ▄▀█ ▄▀█ █░█ █░█ █▀▀ █▀▀
#  █▀█ █▄▄ █░█ █▀█ ██▄ █▄▀ █▀█ █▀█ ▀▄▀ █▀█ █▄▄ █▀░
#
#               Plugin by nmoralesFZ
#             Discord: nmoralesFZ#2607            
#  Descárgalo desde: https://www.nmoralesfz.tk/s/av    



server_ip: "jugar.tuip.com"
scoreb_lines: "" # Separador para la scoreboard (recomendado 15 líneas)
StormBreaker: "&b&lStormBreaker&8» &r&7{time} "
AntiTrapper: "&b&lAntiTrapper&8» &r&7{time} "
Bard: "&b&lZombieBard&8» &r&7{time} "
RogueItem: "&b&lRogue Sword&8» &r&7{time} "
Berserk: "&b&lBerserk&8» &r&7{time} "
EggPort: "&b&lEggPort&8» &r&7{time} "
SpecialItem: "&l&bPartner Item&8» &r&7{time} "
NinjaShear: "&l&bNinjaShear&8» &r&7{time} "
PotionCounter: "&l&bPotionCounter&8» &r&7{time} "
EnderPearl: "&b&lEnderPearl&8» &r&7{time} "
CombatTag: "&b&lCombatTag&8» &r&7{time} "
Apple: "&b&lApple&8» &r&7{time} "
Logout: "&b&lLogout&8» &r&7{time} "
Home: "&b&lHome&8» &r&7{time} "
Stuck: "&b&lStuck&8» &r&7{time} "
SOTW: "&b&lSOTW&8» &r&7{time} "
EOTW: "&b&lEOTW&8» &r&7{time} "
KOTH: "&l&b{kothName}&8» &r&7{time} "
SALE: "&b&lRestart&8» &r&7{time}"
PP: "&l&bPP All in&8» &r&7{time} "
Airdrop: "&l&bAirdrop all in&8» &r&7{time} "
Invincibility: "&b&lPvP Timer&8» &r&7{time} "
BardEnergy: "&b&lBardEnergy&8» &r&c{bardEnergy} "
ArcherEnergy: "&b&lArcherEnergy&8» &r&c{archerEnergy} "
MageEnergy: "&b&lMageEnergy&8» &r&c{mageEnergy} "
factionFocus: [ 
  "&l&bFaction&8» &r&7{factionName} ", 
  "&l&bFocus HQ&8» &r&7{factionHome} ", 
  "&l&bDTR&8» &r&7{factionDTR} ", 
  "&l&bOnline&8» &r&7{factionOnlinePlayers} ", 
]